name: build and test

on:
  push:
  pull_request:
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '5.0.301' # The .NET SDK version to use

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run:  |
        dotnet test --collect:"XPlat Code Coverage" --no-restore --verbosity normal -r TestResults
        ls -al ${{ github.workspace }}
        ls -al ${{ github.workspace }}/TestResults
        ls -al ${{ github.workspace }}/TestResults/*
        mv -v  /home/runner/work/PuttPutt/PuttPutt/TestResults/*/*.coverage.cobertura.xml TestResults/
    
    - run: ls -al ${{ github.workspace }}/test

    - name: Codacy Coverage Reporter
      uses: codacy/codacy-coverage-reporter-action@v1.1.0
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: TestResults/coverage.cobertura.xml
